import LocalizedStrings from 'react-native-localization';

/**
 * Localization
 */
const locales = new LocalizedStrings({
  en: {
    newsBoard: 'News Board',
    publishNews: 'Publish News',
    congressProgram: 'Congress program',
    map: 'Map',
    floorPlan: 'Floor plan',
    contacts: 'Contacts',
    menu: 'Menu',
    croatian: 'Croatian',
    english: 'English',
    german: 'German',
    close: 'Close',
    important: 'Important',
    clubs: 'Nights clubs',
    exchanges: 'Exchange offices',
    sights: 'Sights',
    atm: 'ATM',
    noNews: 'Currently no news',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    auth: 'Login',
    invalidForm: 'Incorrect data',
    email: 'Email',
    password: 'Password',
    login: 'Login',
    logout: 'Logout',
    noInternet: 'No internet connection',
    addNotice: 'New notice',
    publish: 'Publish',
    enterNotice: 'Enter notice',
    newNotice: 'Add new notice',
    emailOrPasswordInvalid: 'Email or password invalid',
    formInvalid: 'Invalid form',
    loggedInAs: 'You are logged in as',
    delete: 'Delete',
    edit: 'Edit',
    notGHappen: "The pretty one doesn't fuck, the tenacious one does, but not this time ;)",
    update: 'Update',
    tripDescription: 'Trip description',
    deleteAlert: 'Notice deleting',
    alertAreYouSure: 'Are you sure you want to delete this notice?',
    cancel: 'Cancel',
    confirm: 'Confirm',
    number: 'Number',
    navigation: 'Navigation',
    navigationAlert: 'By confirm, navigation will start in Google maps',
    mapLocationAlert: "You won't be able to see your location on map",
    mapDropdownLabel: 'Choose what you want to search',
    mapNavigateMe: 'Navigate me to',
    booklet: 'Booklet'
  },
  hr: {
    newsBoard: 'Oglasna ploča',
    publishNews: 'Objava novosti',
    congressProgram: 'Program kongresa',
    map: 'Karta',
    floorPlan: 'Tlocrt faksa',
    contacts: 'Kontakti',
    menu: 'Izbornik',
    croatian: 'Hrvatski',
    english: 'Engleski',
    german: 'Njemački',
    close: 'Zatvori',
    important: 'Važno',
    clubs: 'Noćni klubovi',
    exchanges: 'Mjenjačnice',
    sights: 'Znamenitosti',
    atm: 'Bankomati',
    noNews: 'Trenutno nema novosti',
    monday: 'Ponedjeljak',
    tuesday: 'Utorak',
    wednesday: 'Srijeda',
    thursday: 'Četvrtak',
    friday: 'Petak',
    saturday: 'Subota',
    sunday: 'Nedjelja',
    auth: 'Prijava',
    invalidForm: 'Neispravni podatci',
    email: 'Email',
    password: 'Lozinka',
    login: 'Prijava',
    logout: 'Odjava',
    noInternet: 'Niste povezani na internet',
    addNotice: 'Nova obavijest',
    publish: 'Objavi',
    enterNotice: 'Upišite obavijest',
    newNotice: 'Dodaj novu obavijest',
    emailOrPasswordInvalid: 'Email ili lozinka neispravni',
    formInvalid: 'Neispravni podatci',
    loggedInAs: 'Ulogirani ste kao',
    delete: 'Izbriši',
    edit: 'Uredi',
    notGHappen: 'Ne jebe lijep, nego uporan, ali ne ovaj put ;)',
    update: 'Ažuriraj',
    tripDescription: 'Opis izleta',
    deleteAlert: 'Brisanje obavijesti',
    alertAreYouSure: 'Jeste li sigurni da želite izbrisati ovu obavijest?',
    cancel: 'Odustani',
    confirm: 'Potvrdi',
    number: 'Broj',
    navigation: 'Navigacija',
    navigationAlert: 'Potvrdom pokrećete navigaciju u Google Maps aplikaciji',
    mapLocationAlert: 'Nećete moći vidjeti vašu lokaciju na mapi',
    mapDropdownLabel: 'Izaberite što želite pretražiti',
    mapNavigateMe: 'Navigiraj me do',
    booklet: 'Brošura'
  },
  de: {
    newsBoard: 'Neuigkeiten',
    publishNews: 'Neuigkeit veröffentlichen',
    congressProgram: 'Kongressprogramm',
    map: 'Karte',
    floorPlan: 'Gebäudeplan',
    contacts: 'Kontakte',
    menu: 'Menü',
    croatian: 'Kroatisch',
    english: 'Englisch',
    german: 'Deutsch',
    close: 'Schließen',
    important: 'Wichtig',
    clubs: 'Nachtclubs',
    exchanges: 'Wechselstuben ',
    sights: 'Sehenswürdigkeiten',
    atm: 'ATM',
    noNews: 'Momentan keine Nachrichten',
    monday: 'Montag',
    tuesday: 'Dienstag',
    wednesday: 'Mittwoch',
    thursday: 'Donnerstag',
    friday: 'Freitag',
    saturday: 'Samstag',
    sunday: 'Sonntag',
    auth: 'Anmeldung',
    invalidForm: 'Inkorrekte Daten',
    email: 'Email',
    password: 'Passwort',
    login: 'Anmelden',
    logout: 'Abmelden',
    noInternet: 'Keine Internetverbindung',
    addNotice: 'Neue Mitteilung',
    publish: 'Veröffentlichten',
    enterNotice: 'Geben Sie die Benachrichtigung ein',
    newNotice: 'Neue Benachrichtigung hinzufügen',
    emailOrPasswordInvalid: 'Email or Passwort inkorrekt',
    formInvalid: 'Data inkorrekt',
    loggedInAs: 'Sie sind angemeldet als',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    notGHappen:
      'Es fickt nicht derjenige der schön ist, sondern derjenige der hartnäckig fickt, aber nicht dieses Mal ;)',
    update: 'Update',
    tripDescription: 'Reisebeschreibung',
    deleteAlert: 'Benachrichtigungen löschen',
    alertAreYouSure: 'Möchten Sie diese Benachrichtigung wirklich löschen?',
    cancel: 'Abbrechen',
    confirm: 'Bestätigen',
    number: 'Nummer',
    navigation: 'Navigation',
    navigationAlert: 'Mit der bestätigung starten Sie die Navigation in Google maps',
    mapLocationAlert: 'Sie werden nicht Ihren Standort auf der Karte sehen können',
    mapDropdownLabel: 'Wählen Sie aus, was Sie suchen möchten',
    mapNavigateMe: 'Navigiere mich zu',
    booklet: 'Heft'
  }
});

export default locales;
