export const userActionTypes = Object.freeze({
  AUTH_USER: 'AUTH_USER',
  AUTH_USER_SUCCESS: 'AUTH_USER_SUCCESS',
  AUTH_USER_ERROR: 'AUTH_USER_ERROR',
  LOG_OUT: 'LOG_OUT'
});

export const uiActionTypes = Object.freeze({
  START_ACTION: 'START_ACTION',
  STOP_ACTION: 'STOP_ACTION',
  REFRESH_ACTION_START: 'REFRESH_ACTION_START',
  REFRESH_ACTION_STOP: 'REFRESH_ACTION_STOP',
  TOGGLE_POPUP_MESSAGE: 'TOGGLE_POPUP_MESSAGE'
});

export const localeActionTypes = Object.freeze({
  CHANGE_LOCALE: 'CHANGE_LOCALE',
  CHANGE_LOCALE_SUCCESS: 'CHANGE_LOCALE_SUCCESS'
});

export const newsActionTypes = Object.freeze({
  FETCH_NEWS: 'FETCH_NEWS',
  FETCH_NEWS_SUCCESS: 'FETCH_NEWS_SUCCESS',
  FETCH_NEWS_ERROR: 'FETCH_NEWS_ERROR',
  PUBLISH_NEWS: 'PUBLISH_NEWS',
  PUBLISH_NEWS_SUCCESS: 'PUBLISH_NEWS_SUCCESS',
  UPDATE_NEWS: 'UPDATE_NEWS',
  UPDATE_NEWS_SUCCESS: 'UPDATE_NEWS_SUCCESS',
  DELETE_NEWS: 'DELETE_NEWS',
  DELETE_NEWS_SUCCESS: 'DELETE_NEWS_SUCCESS'
});
